name: CI Workflow using Docker
on: push
env:
 DOCKER_IMAGE_NAME: my-tomcat-app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - name: Install JAVA
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Create WAR file
      run: mvn -B package --file pom.xml
    - name: Install Docker
      uses: docker/setup-docker-action@v4.2.0
    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build and Push Image
      uses: docker/build-push-action@v6.15.0
      with:
        context: .
        push: true
        tags: ${{ vars.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
      
 
